language: node_js

node_js:
  - '10'

script:
  - mkdir dist
  - touch dist/test

before_install:


addons:
  ssh_known_hosts:
    - www.aqcoder.com

after_success:
  - openssl aes-256-cbc -K $encrypted_a0644cfc0fcc_key -iv $encrypted_a0644cfc0fcc_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - scp -P29371 -r dist/* www.aqcoder.com:/var/www/gvf-admin/
