language: node_js

node_js:
  - '10'

script:
  - yarn build

before_install:
  - openssl aes-256-cbc -K $encrypted_a0644cfc0fcc_key -iv $encrypted_a0644cfc0fcc_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - www.aqcoder.com:$sshport

deploy:
  provider: script
  script: scp -P$sshport -r dist/* www.aqcoder.com:/var/www/gvf-admin/
  skip_cleanup: true
